[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "A Hugo Theme"
    [en.params.feature]
        link = "docs/0.9/getting-started/introduction/"
        caption = "Get Started"
    [en.params.demo]
        link = "https://demo.gethinode.com"
        caption = "Live Demo"
    [en.params.footer]
        license = "<a href='https://github.com/gethinode/hinode/blob/main/LICENSE' class='link-bg-secondary' target='_blank'>MIT license</a>"