[main]
    separator = "-"
    description = "Hinode is a clean documentation and blog theme for your Hugo site based on Bootstrap 5."
    enableDarkMode = true

[docs]
    version = "0.9"
    basePath = "node_modules/@gethinode/hinode"

[home]
    sections = ["features"]
    # sections = ["features", "releases"]
    fullCover = true
    style = "gradient-featured"

[navigation]
    logo = "/img/logo_icon.svg"
    color = ""
    fixed = true
    offset = "4em"
    search = true
    breadcrumb = false
    toc = true
    sidebar = true

[list]
    [features]
        title = ""
        sort = "weight"
        reverse = false
        cols = 3
        color = ""
        padding = "3"
        header = "none"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-emphasize card-feature"
        homepage = 6
        background = "body"
    # [releases]
    #     title = "Releases"
    #     sort = "date"
    #     reverse = false
    #     cols = 3
    #     color = ""
    #     padding = "0"
    #     header = "full"
    #     footer = "none"
    #     orientation = "stacked"
    #     style = "border-0"
    #     homepage = 3

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#D43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    themeFont = "Inter"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap"

[schema]
    type = "Organization"
    name = "Hinode"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/gethinode/hinode"
    section = "blog"
    [author]
        name = "Mark Dumay"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/in/markdumay/"
        github = "https://github.com/markdumay"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

[comments]
    enabled = false
    repo = "" # Replace with your repository.
    #issueTerm = "pathname" # pathname, url, title, og:title
    #label = "comment"
    # By default, light and dark mode correspond to github-light and github-dark, respectively.
    # Optional values: github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.
    #theme = "" 

[links]
    azure = "https://azure.microsoft.com"
    az_blob_domain = "https://learn.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name"
    az_blob_pricing = "https://azure.microsoft.com/en-us/free"
    az_cdn_rules = "https://learn.microsoft.com/en-us/azure/cdn/cdn-standard-rules-engine-reference"
    blist = "https://github.com/apvarun/blist-hugo-theme"
    bootstrap = "https://getbootstrap.com"
    bs_badge_heading = "https://getbootstrap.com/docs/5.2/components/badge/#headings"
    bs_breakpoints = "https://getbootstrap.com/docs/5.3/layout/breakpoints"
    bs_color = "https://getbootstrap.com/docs/5.3/customize/color-modes"
    bs_color_sass = "https://getbootstrap.com/docs/5.3/customize/color-modes/#building-with-sass"
    bs_grid = "https://getbootstrap.com/docs/5.3/layout/grid"
    bs_offcanvas = "https://getbootstrap.com/docs/5.3/components/offcanvas"
    bs_navbar_placement = "https://getbootstrap.com/docs/5.3/components/navbar/#placement"
    bs_tables = "https://getbootstrap.com/docs/5.3/content/tables"
    cc_by_nc_4_0 = "https://creativecommons.org/licenses/by-nc/4.0/"
    cloudflare = "https://cloudflare.com"
    commit_message = "https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html"
    contrast_checker = "https://accessibleweb.com/color-contrast-checker/"
    css_codeguide = "https://codeguide.co/#css"
    doks = "https://github.com/h-enk/doks"
    eslint = "https://eslint.org"
    flexsearch = "https://github.com/nextapps-de/flexsearch"
    fontawesome = "https://fontawesome.com"
    fa_icons = "https://fontawesome.com/icons"
    fa_styling = "https://fontawesome.com/docs/web/style/styling"
    fa_animation = "https://fontawesome.com/docs/web/style/animate"
    git_download = "https://git-scm.com"
    github_pr = "https://help.github.com/articles/about-pull-requests/"
    github_rebase = "https://help.github.com/articles/about-git-rebase/"
    google_fonts = "https://fonts.google.com"
    html_codeguide = "https://codeguide.co/#html"
    hugo = "https://gohugo.io"
    hugo_config = "https://gohugo.io/getting-started/configuration/#all-configuration-settings"
    hugo_config_dir = "https://gohugo.io/getting-started/configuration/#configuration-directory"
    hugo_content = "https://gohugo.io/content-management/formats"
    hugo_chroma = "https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages"
    hugo_deploy = "https://gohugo.io/hosting-and-deployment/hugo-deploy"
    hugo_deployment = "https://gohugo.io/hosting-and-deployment"
    hugo_config_deploy = "https://gohugo.io/hosting-and-deployment/hugo-deploy/#configure-the-deployment"
    hugo_fingerprint = "https://gohugo.io/hugo-pipes/fingerprint"
    hugo_frontmatter = "https://gohugo.io/content-management/front-matter"
    hugo_i18n = "https://gohugo.io/functions/i18n"
    hugo_image = "https://gohugo.io/content-management/image-processing"
    hugo_lang = "https://gohugo.io/content-management/multilingual"
    hugo_lang_config = "https://gohugo.io/content-management/multilingual/#configure-languages"
    hugo_links = "https://gohugo.io/content-management/cross-references"
    hugo_menus = "https://gohugo.io/content-management/menus/"
    hugo_mounts = "https://gohugo.io/hugo-modules/configuration/#module-config-mounts"
    hugo_imaging = "https://gohugo.io/content-management/image-processing/#imaging-configuration"
    hugo_ordering = "https://gohugo.io/templates/lists/#order-content"
    hugo_shortcodes = "https://gohugo.io/content-management/shortcodes"
    hugo_structure = "https://gohugo.io/content-management/organization"
    hugo_templates = "https://gohugo.io/templates/introduction"
    hugo_lookup_order = "https://gohugo.io/templates/lookup-order"
    hugo_toc = "https://gohugo.io/content-management/toc"
    issue_tracker = "https://github.com/gethinode/hinode/issues"
    license = "https://github.com/gethinode/hinode/blob/main/LICENSE"
    markdown_guide = "https://www.markdownguide.org"
    markdown_emoji = "https://gist.github.com/rxaviers/7360908"
    markdown_md013 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length"
    markdown_md024 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content"
    markdown_md026 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading"
    markdown_md033 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html"
    markdown_md034 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034---bare-url-used"
    markdown_md051 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md051---link-fragments-should-be-valid"
    markdown_md053 = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md053---link-and-image-reference-definitions-should-be-needed"
    markdown_rules = "https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md"
    markdownlint = "https://github.com/DavidAnson/markdownlint-cli2"
    mozilla_image = "https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images"
    netlify = "https://www.netlify.com"
    netlify_cache= "https://www.netlify.com/blog/2017/02/23/better-living-through-caching/"
    nodejs = "https://nodejs.org"
    npm = "https://www.npmjs.com"
    observatory = "https://observatory.mozilla.org/analyze/demo.gethinode.com"
    package_npm = "https://www.npmjs.com/package/@gethinode/hinode"
    pagespeed = "https://pagespeed.web.dev/report?url=https%3A%2F%2Fdemo.gethinode.com%2F"
    repository = "https://github.com/gethinode/hinode"
    repository_child = "https://github.com/gethinode/child.git"
    repository_owner = "https://github.com/gethinode/"
    semver = "https://semver.org"
    stylelint = "https://stylelint.io"
    utterances = "https://utteranc.es"
    wcag_contrast = "https://www.w3.org/TR/WCAG20/#visual-audio-contrast"