[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 20

[[main]]
  name = "Components"
  url = "/components/"
  weight = 30

[[main]]
  name = "Guides"
  url = "/guides/"
  weight = 40

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  url = "/en/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  url = "/en/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Home"
  url = "/"
  weight = 1

[[footer]]
  parent = "Links"
  name = "About"
  url = "/about/"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Docs"
  url = "/docs/"
  weight = 20

[[footer]]
  parent = "Links"
  name = "Components"
  url = "/components/"
  weight = 30

[[footer]]
  name = "Guides"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Getting started"
  url = "/guides/editing"
  weight = 10

[[footer]]
  parent = "Guides"
  name = "Adding packages"
  url = "/guides/packages"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Optimization"
  url = "/guides/optimization"
  weight = 30

[[footer]]
  name = "Community"
  weight = 30

[[footer]]
  parent = "Community"
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 10

[[footer]]
  parent = "Community"
  name = "Issues"
  url = "https://github.com/gethinode/hinode/issues"
  weight = 20

[[footer]]
  parent = "Community"
  name = "Contribute"
  url = "/contribute"
  weight = 30
