[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Docs"
  url = "/docs/"
  weight = 20

[[main]]
  name = "Guides"
  url = "/guides/"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 40

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  url = "/en/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  url = "/en/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation