[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10
  [main.params]
    alias = true

[[main]]
  name = "Docs"
  pageRef = "/docs/"
  weight = 20

[[main]]
  name = "Components"
  pageRef = "/components/"
  weight = 30
  [main.params]
    alias = true

[[main]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 40

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "About"
  pageRef = "/about/"
  weight = 10
  [sample.params]
    alias = true

[[sample]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 30

[[sample]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing/"
  weight = 10

[[sample]]
  parent = "Guides"
  name = "Adding packages"
  pageRef = "/guides/packages/"
  weight = 20

[[sample]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization/"
  weight = 30

[[sample]]
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 40
# toml-docs-end sample-navigation

[[alias]]
  name = "About"
  pageRef = "/about/"
  weight = 10
  [alias.params]
    alias = true

[[alias]]
  name = "About (no alias)"
  pageRef = "/about/"
  weight = 20

[[alias]]
  name = "Guides"
  pageRef = "/guides/"
  weight = 30

[[alias]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing/"
  weight = 10

[[alias]]
  parent = "Guides"
  name = "Adding packages"
  pageRef = "/guides/packages/"
  weight = 20

[[alias]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization/"
  weight = 30

[[alias]]
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 40

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Home"
  pageRef = "/"
  weight = 1

[[footer]]
  parent = "Links"
  name = "About"
  pageRef = "/about/"
  weight = 10
  [footer.params]
    alias = true

[[footer]]
  parent = "Links"
  name = "Docs"
  pageRef = "/docs/"
  weight = 20

[[footer]]
  parent = "Links"
  name = "Components"
  pageRef = "/components/"
  weight = 30
  [footer.params]
    alias = true

[[footer]]
  name = "Guides"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Getting started"
  pageRef = "/guides/editing"
  weight = 10

[[footer]]
  parent = "Guides"
  name = "Adding packages"
  pageRef = "/guides/packages"
  weight = 20

[[footer]]
  parent = "Guides"
  name = "Optimization"
  pageRef = "/guides/optimization"
  weight = 30

[[footer]]
  name = "Community"
  weight = 30

[[footer]]
  parent = "Community"
  name = "GitHub"
  url = "https://github.com/gethinode/hinode"
  weight = 10

[[footer]]
  parent = "Community"
  name = "Discussions"
  url = "https://github.com/gethinode/hinode/discussions"
  weight = 20

[[footer]]
  parent = "Community"
  name = "Contribute"
  pageRef = "/contribute"
  weight = 30
